# Generated by Django 3.2.5 on 2021-07-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='day',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
