# Generated by Django 3.2.5 on 2021-08-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20210802_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], default='1', max_length=1),
        ),
    ]
