# Generated by Django 3.2.5 on 2021-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
