# Generated by Django 3.2.5 on 2021-08-24 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20210802_0929'),
        ('assignment', '0002_submission_checked'),
    ]

    operations = [
    ]
