# Generated by Django 3.2.5 on 2021-07-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_remove_assignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='onTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
