# Generated by Django 3.2.5 on 2021-07-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_auto_20210714_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
