# Generated by Django 3.2.5 on 2021-07-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_alter_submission_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='comment',
        ),
    ]
