# Generated by Django 3.2.5 on 2021-07-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_remove_submission_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
